package projeto1;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;

public class Janela extends javax.swing.JFrame {
    //====================\\
    //===[DECLARATIONS]===\\
    //====================\\
    
    public short multiplier = 1;
    
    //===================\\
    //===[CONSTRUCTOR]===\\
    //===================\\
    
    public Janela() {
        initComponents();
        
        //Save game when closing the window
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                //Try to save the game
                try{
                    //Create player stats and call to save
                    PlayerStats ps = new PlayerStats();
                    ps.SaveData();
                    
                    //Print when saved
                    System.out.println("SALVO COM SUCESSO");
                }catch(Exception ex){
                    Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        potatoMult = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        buildings = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        killedLeftists = new javax.swing.JLabel();
        governmentActivity = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextArea4 = new javax.swing.JTextArea();
        destroyGovernment = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        takedownCost = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        leftistQnt = new javax.swing.JLabel();
        killLeftist = new javax.swing.JButton();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        killLeftCost = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        taxValue = new javax.swing.JLabel();
        taxTime = new javax.swing.JLabel();
        payTax = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        announcementsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Potato Game");
        setResizable(false);

        potatoMult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x", "10x", "100x", "1000x" }));
        potatoMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potatoMultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(potatoMult, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(potatoMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Batatas", jPanel3);

        jScrollPane2.setBorder(null);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(649, 562));

        buildings.setPreferredSize(new java.awt.Dimension(630, 0));

        javax.swing.GroupLayout buildingsLayout = new javax.swing.GroupLayout(buildings);
        buildings.setLayout(buildingsLayout);
        buildingsLayout.setHorizontalGroup(
            buildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        buildingsLayout.setVerticalGroup(
            buildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(buildings);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Produtores", jPanel1);

        jPanel9.setAutoscrolls(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel32.setText("Governo:");

        jLabel33.setText("Esquerdistas Mortos:");

        killedLeftists.setText("0");

        governmentActivity.setText("Ativo");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(governmentActivity)
                    .addComponent(killedLeftists))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(governmentActivity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(killedLeftists))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Status", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel6.setPreferredSize(new java.awt.Dimension(237, 174));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("DESTRUIR GOVERNO");

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Se você destruir o governo, você não precisará pagar mais impostos. Mas esquerdistas separatistas irão começar a surgir.");
        jTextArea4.setWrapStyleWord(true);

        destroyGovernment.setText("Destruir Governo !");
        destroyGovernment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destroyGovernmentActionPerformed(evt);
            }
        });

        jLabel25.setText("Custo:");

        takedownCost.setText("TD$ 907470999.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextArea4)
                    .addComponent(destroyGovernment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takedownCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(takedownCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destroyGovernment)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel7.setPreferredSize(new java.awt.Dimension(240, 174));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ESQUERDISTAS");

        jLabel7.setText("Esquerdistas protestando:");

        leftistQnt.setText("0");

        killLeftist.setText("Matar 1 Esquerdista");
        killLeftist.setEnabled(false);
        killLeftist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                killLeftistActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Quando o número de esquerdistas protestando atingir 100, o governo voltará a ativa. Seus Temeres Delatados e batatas serão zerados e o imposto voltará com seu valor dobrado.\n\n");
        jTextArea3.setWrapStyleWord(true);

        jLabel29.setText("Custo:");

        killLeftCost.setText("TD$ 8474740.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(killLeftist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextArea3)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leftistQnt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(killLeftCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(leftistQnt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(killLeftCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(killLeftist)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Governo", jPanel5);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel12);

        jTabbedPane2.addTab("Loja", jScrollPane4);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel10);

        jTabbedPane2.addTab("Inventário", jScrollPane1);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("The Potato Game");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel3.setText("Temeres Delatados: TD$");

        money.setText("6666");

        jLabel18.setText("IMPOSTO (Roubo): TD$");

        jLabel20.setText("Você será roubado em: ");

        taxValue.setText("999");

        taxTime.setText("1:00");

        payTax.setText("Pagar Imposto Antecipado");
        payTax.setToolTipText("Se você pagar o imposto antecipado, o próximo roubo será daqui a 3 minutos, ao invés de 1.");
        payTax.setEnabled(false);
        payTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payTaxActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Avisos"));

        announcementsLabel.setText("Bem Vindos ao Potato Game! Comece o jogo comprando uma Fazenda!");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(announcementsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(announcementsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(payTax, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(money)
                    .addComponent(jLabel18)
                    .addComponent(taxValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(taxTime)
                    .addComponent(payTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //========================\\
    //===[BUTTON FUNCTIONS]===\\
    //========================\\
    
    //The user has clicked to pay his taxes early
    private void payTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payTaxActionPerformed
        if(Game.money.compareTo(Game.government.taxValue) >= 0){
            Game.GiveMoney(Game.government.taxValue.negate());
            Game.government.ChangeTaxTime(180);
        }else{
            Announcements.DisplayAnnouncement("Você não tem dinheiro o suficiente para pagar o imposto!", Announcements.TextStyles.CriticalAlert);
        }
    }//GEN-LAST:event_payTaxActionPerformed

    private void killLeftistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_killLeftistActionPerformed
        //Kill a leftist if the player has the money
        if(Game.money.compareTo(Game.government.killLeftCost) >= 0 && Game.government.leftists > 0){
            Game.government.AddLeftist(-1);
        }else{
            //Display announcement if there is no leftist
            if(Game.government.leftists == 0)
                Announcements.DisplayAnnouncement("Por enquanto não existe nenhum esquerdista vivo!", Announcements.TextStyles.CriticalAlert);
            //Display announcement if the player doesn't have money
            else
                Announcements.DisplayAnnouncement("Você não tem dinheiro o suficiente para matar 1 esquerdista!", Announcements.TextStyles.CriticalAlert);
        }
            
    }//GEN-LAST:event_killLeftistActionPerformed

    private void destroyGovernmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destroyGovernmentActionPerformed
        if(Game.money.compareTo(Game.government.takedownCost) >= 0){
            //Deactivate the government
            Game.government.DeactivateGovernment();
            
            //Take the money
            Game.GiveMoney(Game.government.takedownCost.negate());
            
            //Display announcement
            Announcements.DisplayAnnouncement("Você derrubou o governo! Um movimento esquersista está em ascensão!", Announcements.TextStyles.GoodAlert);
        } else
            Announcements.DisplayAnnouncement("Você não tem dinheiro o suficiente para derrubar o governo", Announcements.TextStyles.CriticalAlert);
        
    }//GEN-LAST:event_destroyGovernmentActionPerformed

    //The user has changed an item from the multiplier
    private void potatoMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potatoMultActionPerformed
        //Change the multiplier depending the setting that the player has defined
        switch(potatoMult.getSelectedItem()+""){
            case "1x":
            multiplier = 1;

            break;
            case "10x":
            multiplier = 10;

            break;
            case "100x":
            multiplier = 100;

            break;
            case "1000x":
            multiplier = 1000;

            break;
        }

        //Update UI
        for(Potatoes potato : Potatoes.allPotatoes){
            potato.potatoUi.potatoPriceUI.setText(Utils.stringifyBD(potato.currentPrice.multiply(new BigDecimal(multiplier)))+"");
        }
    }//GEN-LAST:event_potatoMultActionPerformed

    //===============\\
    //===[METHODS]===\\
    //===============\\
    
    //Creates the layout for the buildings menu
    void CreateBuildingMenuLayout(Building[] allBuildings){
        //Table to store all of the building UIs
        JComponent[] buildingUIs = new JComponent[allBuildings.length];
        
        //Add components to the menu
        for (int i = 0; i < allBuildings.length; i++)
            buildingUIs[i] = allBuildings[i].buildingShop;
        
        //Build grid
        CreateGridLayout(buildings, buildingUIs, 3, 20, 10, 30, 10);
    }
    
    //Creates the potato menu
    void CreatePotatoMenu(Potatoes[] allPotatoes){
        //Set the layout
        jPanel3.setLayout(null);
        
        for (int i = 0; i < allPotatoes.length; i++) {
            //Add the ui to the menu and show them
            jPanel3.add(allPotatoes[i].potatoUi);
            allPotatoes[i].potatoUi.setVisible(true);
            
            //Set the location
            allPotatoes[i].potatoUi.setLocation(10, 10 + (i * 23) + (i * 5));
        }
    }
    
    //Fills the status menu
    void FillBuildingPotatoStatus(){
        //Set layout of the status
        jPanel4.setLayout(null);
        
        //Create the production status of the potatoes
        for (int i = 0; i < Potatoes.allPotatoes.length; i++) {
            //The text that will be shown
            String labelText = "Produção > Batata " + Potatoes.allPotatoes[i].name;
            String valueText = Potatoes.allPotatoes[i].production + " b/s";
            
            //Rectangle
            Rectangle labelRectangle = new Rectangle(10, 20 * i + 10, 153, 20);
            Rectangle valueRectangle = new Rectangle(174, 20 * i + 10, 289-174, 20);
            
            //Create UI and set the production UI
            Potatoes.allPotatoes[i].productionUI = CreateStatusLabel(labelText, valueText, labelRectangle, valueRectangle);
        }
        
        //Create the production status of the buildings
        for (int i = 0; i < Building.allBuildings.length; i++) {
            //The text that will be shown
            String labelText = "Produção > " + Building.allBuildings[i].buildingName;
            String valueText = Building.allBuildings[i].potatoProduction * Building.allBuildings[i].buildingQnt+" b/s";
            
            //Rectangle
            Rectangle labelRectangle = new Rectangle(10, 20 * Potatoes.allPotatoes.length + 20 + 20 * i, 153, 20);
            Rectangle valueRectangle = new Rectangle(174, 20 * Potatoes.allPotatoes.length + 20 + 20 * i, 289-174, 20);
            
            //Finalize
            Building.allBuildings[i].productionUI = CreateStatusLabel(labelText, valueText, labelRectangle, valueRectangle);
        }
        
        //Set the size of the panel
        jPanel4.setPreferredSize(new Dimension(289, 20*Potatoes.allPotatoes.length + 30 + 20*Building.allBuildings.length));
    }
    
    //Fills the inventory
    void FillInventory(){
        //Table to store all of the items inventory UI
        JComponent[] allItemsInvUI = new JComponent[Item.allItems.length];
        
        //Get all of the inventory UI of the items and store them on the table
        for (int i = 0; i < allItemsInvUI.length; i++)
            allItemsInvUI[i] = Item.allItems[i].invUI;
        
        //Create the grid layout for the inventory
        CreateGridLayout(jPanel10, allItemsInvUI, 4, 25, 10, 15, 10);
    }
    
    //Fills the inventory
    void FillShop(){
        //Table to store all of the items inventory UI
        List<JComponent> allItemsShopUI = new ArrayList<>();
        
        //Get all of the inventory UI of the items and store them on the table
        for (Item item : Item.allItems) {
            if (item.shopUI != null) {
                allItemsShopUI.add(item.shopUI);
            }
        }
        
        //Convert List to regular Array
        JComponent[] jcompArray = new JComponent[allItemsShopUI.size()];
        jcompArray = allItemsShopUI.toArray(jcompArray);
        
        //Create the grid layout for the inventory
        CreateGridLayout(jPanel12, jcompArray , 3, 25, 10, 20, 10);
    }
    
    //=======================\\
    //===[PRIVATE METHODS]===\\
    //=======================\\
    
    //Creates a grid
    private void CreateGridLayout(JComponent gridComp, JComponent[] gridItems, int qntRow, int startXGap, int startYGap, int itemsGapX, int itemsGapY){
        //Set the layout of the component that we will be filling
        gridComp.setLayout(null);
        
        int gridCompHeight = 0;
        int gridCompWidth = 0;
        for (int i = 0; i < gridItems.length; i++) {
            JComponent gItem = gridItems[i];
            
            //Add the grid item to the grid
            gridComp.add(gItem);

            //Define the X and Y position of the gridItem
            int x = startXGap + (i % qntRow * gItem.getWidth()) + (i % qntRow * itemsGapX);
            int y = startYGap + (i / qntRow * gItem.getHeight()) + (i / qntRow * itemsGapY);
            
            //Set the layout
            gItem.setLocation(x, y);
            
            //Set the height for the grid component
            if(gridCompHeight < gItem.getY() + gItem.getHeight())
                gridCompHeight = gItem.getY() + gItem.getHeight();
            
            //Set the width of the grid component
            if(gridCompWidth < gItem.getX() + gItem.getWidth())
                gridCompWidth = gItem.getX() + gItem.getWidth();
        }
        
        //Set the size of the inner frame
        gridComp.setPreferredSize(new Dimension(gridCompWidth, gridCompHeight));
    }
    
    //Creates a production stat label
    private JLabel CreateStatusLabel(String statName, String statValue, Rectangle statNameRec, Rectangle statValueRec){
        //Create JLabel
        JLabel productionLabel = new JLabel();
        JLabel production = new JLabel();

        //Set the texts
        productionLabel.setText(statName);
        productionLabel.setToolTipText(statName);
        production.setText(statValue);

        //Add the UI to the panel
        jPanel4.add(productionLabel);
        jPanel4.add(production);

        //Set them visible
        productionLabel.setVisible(true);
        production.setVisible(true);

        //Set the position and size
        productionLabel.setBounds(statNameRec);
        production.setBounds(statValueRec);
        
        return production;
    }
    
    //=======================\\
    //===[UI DECLARATIONS]===\\
    //=======================\\
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel announcementsLabel;
    javax.swing.JPanel buildings;
    public javax.swing.JButton destroyGovernment;
    public javax.swing.JLabel governmentActivity;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    public javax.swing.JLabel killLeftCost;
    public javax.swing.JButton killLeftist;
    public javax.swing.JLabel killedLeftists;
    public javax.swing.JLabel leftistQnt;
    public javax.swing.JLabel money;
    public javax.swing.JButton payTax;
    private javax.swing.JComboBox<String> potatoMult;
    public javax.swing.JLabel takedownCost;
    public javax.swing.JLabel taxTime;
    public javax.swing.JLabel taxValue;
    // End of variables declaration//GEN-END:variables
}